Update to the recent version of quda
Lyncs-API/lyncs.quda pull request #7
Opened 2023-01-10 16:26 UTC by sy3394

2023-01-10 16:36 UTC, sbacchio requested changes

2023-01-10 16:36 UTC, sbacchio commented on lyncs_quda/array.py
> +    def __setitem(self, i, val):
change to `__setitem__`

2023-01-10 16:36 UTC, sbacchio commented on lyncs_quda/array.py
> +                self._qarray[0] = elems
if only one given maybe we want to set all to that value?

2023-01-10 16:36 UTC, sbacchio commented on lyncs_quda/include/.gitignore
> -!evenodd.h
This should be restored

2023-01-10 16:37 UTC, sbacchio commented on lyncs_quda/array.py
> +                    self._qarray[i] = e
Since you define `__setitem__`, then you can use directly `self[i]=e`

2023-01-10 16:40 UTC, sbacchio commented on lyncs_quda/array.py
> +    return Array(int, 6, elems).qarray
instead of `6` I guess you could use lib.QUDA_MAX_DIM

2023-01-12 06:53 UTC, sbacchio commented on lyncs_quda/array.py
> +        return self._size
Would be nice if size is taken directly from qarray

2023-01-12 07:06 UTC, sbacchio commented
@sy3394 I took care some of the changes and I left comments that still need to be addressed.
I am going to test it. If everything works fine we can merge it!

2023-01-23 14:35 UTC, sbacchio commented
@sy3394 I did some more work on this PR, please have a look.
For now it is working fine with my software stack so we could merge it in soon.

2023-01-30 18:02 UTC, sy3394 commented on lyncs_quda/gauge_field.py
> +                raise ValueError(f"Path {i} = {path} nevative first movement")
nevative -> negative

2023-01-30 18:02 UTC, sy3394 commented on lyncs_quda/gauge_field.py
> +        count = defaultdict(int)
where is this used?

2023-01-30 18:02 UTC, sy3394 commented on lyncs_quda/gauge_field.py
>          Computes the gauge paths on the lattice.
This is a comment for description following this line, which is not showing up here.
It says:
"
- The paths are given with respect to direction "1" and
          this must be the first number of every path list.
        - Directions go from 1 to self.ndims
        - Negative value (-1,...) means backward movement in the direction
        - Paths are then rotated for every direction.
"
Does this suggest that the input "paths" is, e.g., a list of list of integers where the the first element of each list in paths should always be 1?  Then, rotation over other directions are performed on each path.  Is my understanding correct?  If so, this should be checked by _check_paths(self, paths), although the code suggests this is not what is done.

2023-01-31 06:45 UTC, sbacchio commented on lyncs_quda/gauge_field.py
>          Computes the gauge paths on the lattice.
Your understanding is correct, but that comment it is outdated. This was the old implementation. I will fix it.. and thanks also for catching the other issues

2023-01-31 07:06 UTC, sbacchio approved these changes
Looks good to me. @sy3394 if you don't have further comments, please merge!

2023-01-31 15:17 UTC, sy3394 reviewed
just one small suggestion for readability.

2023-01-31 15:17 UTC, sy3394 commented on lyncs_quda/gauge_field.py
> +        The paths are list of integers with the following structure
How about "A path is a list of ...".  To me, that's easier to grasp.

2023-02-01 11:41 UTC, merged